name: Deploy-GH-Pages

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: latest

      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'

      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
          cache: 'pip'

      - name: Setup python
        run: pip install -r requirements.txt

      # - name: Validate catalog items
      #   run: python scripts/validate_catalog.py
      #   env:
      #     GSTORAGE_API_KEY: ${{ secrets.GSTORAGE_API_KEY }}

      - name: Install dependencies
        run: pnpm i && cp .env.github .env

      # - name: Merge catalog entries
      #   run: python scripts/transform_catalog.py && python scripts/transform_featured.py
      #   env:
      #     GSTORAGE_API_KEY: ${{ secrets.GSTORAGE_API_KEY }}

      - name: Build project
        run: pnpm build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
