name: Validate catalog items

on:
  pull_request:
    paths:
      - 'catalog/**.yml'

  push:
    branches: [master]
    paths:
      - 'catalog/**.yml'

  workflow_dispatch:

jobs:
  validate-catalog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
          cache: 'pip'

      - run: pip install -r requirements.txt
      # - run: python scripts/validate_catalog.py
      #   env:
      #     GSTORAGE_API_KEY: ${{ secrets.GSTORAGE_API_KEY }}
